name: workflow overview

on:
 workflow_dispatch:

jobs:
 a_simple_job:
  name: my simple job name
  runs-on: ubuntu-latest
  steps:
   - name: name of my step
     id: stepId
     run: echo "This is the fitst step from the firts job"
   - name: step with another shell
     id: sheelDtep
     shell: python
     run: print("this step is using the phthon shell")
